Fix test failures due to kwargs differences
We were seeing test failures such as:

```
Error:
Slimmer::Railtie#test_0002_gets the app name from module_parent_name when the app name is not set in the environment:
ArgumentError: mocked method :use expects 2 arguments, got [Slimmer::App]
    test/railtie_test.rb:39:in `block (3 levels) in <top (required)>'
    test/railtie_test.rb:33:in `block (2 levels) in <top (required)>'
```

These were occurring because the slimmer_config hash argument was being
interpreted as a keyword arguments in Ruby 2.7. In Ruby 3 hashes are no
longer converted to keyword arguments so this change would no longer be
needed.